// ============================================================
// Puzzle Levels - 레벨 데이터 정의
// ============================================================

const LEVELS = [
    // ==========================================================
    // STAGE 1: Vim 기초
    // ==========================================================

    // --- Chapter 1: 기본 이동 ---
    {
        id: 1,
        stage: 1,
        title: '첫 걸음',
        chapter: '이동의 기초',
        description: 'l 키로 커서를 오른쪽으로 움직이고\nx로 불필요한 글자를 삭제하세요.',
        initialText: 'heXllo',
        targetText: 'hello',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['h', 'l', 'x'],
        maxMoves: 5,
        hint: 'l을 두 번 눌러 X 위치로 → x로 삭제',
        newCommands: ['h', 'l', 'x'],
    },
    {
        id: 2,
        stage: 1,
        title: '삽입과 삭제',
        chapter: '이동의 기초',
        description: 'x로 삭제, i로 삽입 모드에 진입하세요.\n삽입 후 Esc로 일반 모드로 돌아옵니다.',
        initialText: 'hllo',
        targetText: 'hello',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['h', 'l', 'x', 'i'],
        maxMoves: 3,
        hint: 'l로 l 위치 이동 → i로 삽입 모드 → e 입력 → Esc',
        newCommands: ['i'],
    },
    {
        id: 3,
        stage: 1,
        title: '상하좌우',
        chapter: '이동의 기초',
        description: 'j, k로 상하 이동을 배워봅시다.\n각 줄의 끝에 있는 X를 삭제하세요.',
        initialText: 'catX\ndogX\nfox',
        targetText: 'cat\ndog\nfox',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['h', 'j', 'k', 'l', 'x'],
        maxMoves: 10,
        hint: 'l로 이동 → x로 삭제 → j로 다음 줄',
        newCommands: ['j', 'k'],
    },

    // --- Chapter 2: 빠른 이동 ---
    {
        id: 4,
        stage: 1,
        title: '워프 점프',
        chapter: '빠른 이동',
        description: 'w, b로 단어 단위로 빠르게 이동하세요.\n마지막 단어의 오타를 수정하세요.',
        initialText: 'the quick fax',
        targetText: 'the quick fox',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['w', 'b', 'h', 'l', 'x', 'i'],
        maxMoves: 6,
        hint: 'w를 두 번 → l로 a에 이동 → x → i → o 입력',
        newCommands: ['w', 'b'],
    },
    {
        id: 5,
        stage: 1,
        title: '줄의 끝과 처음',
        chapter: '빠른 이동',
        description: '0과 $로 줄의 시작과 끝으로 점프하세요.\n양 끝의 점을 제거하세요.',
        initialText: '.hello.',
        targetText: 'hello',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['0', '$', 'h', 'l', 'x'],
        maxMoves: 4,
        hint: 'x → $ → x',
        newCommands: ['0', '$'],
    },

    // --- Chapter 3: 삭제 마스터 ---
    {
        id: 6,
        stage: 1,
        title: '줄 삭제',
        chapter: '삭제 마스터',
        description: 'dd로 필요 없는 줄을 통째로 삭제하세요.',
        initialText: 'keep this\ndelete me\nkeep this too\ndelete me too',
        targetText: 'keep this\nkeep this too',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['j', 'k', 'dd'],
        maxMoves: 4,
        hint: 'j로 이동 → dd로 삭제 → 다시 dd',
        newCommands: ['dd'],
    },
    {
        id: 7,
        stage: 1,
        title: '정밀 삭제',
        chapter: '삭제 마스터',
        description: 'x와 dd를 조합하여 텍스트를 정리하세요.',
        initialText: 'aab\nremove\nddef',
        targetText: 'ab\ndef',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['h', 'j', 'k', 'l', 'x', 'dd'],
        maxMoves: 5,
        hint: 'x로 중복 삭제 → j → dd → x로 정리',
        newCommands: [],
    },

    // --- Chapter 4: 삽입의 기술 ---
    {
        id: 8,
        stage: 1,
        title: '끝에 추가',
        chapter: '삽입의 기술',
        description: 'A로 줄 끝에 텍스트를 추가하세요.',
        initialText: 'hello\nworld',
        targetText: 'hello!\nworld!',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['j', 'k', 'A'],
        maxMoves: 4,
        hint: 'A → ! 입력 → Esc → j → A → !',
        newCommands: ['A'],
    },
    {
        id: 9,
        stage: 1,
        title: '새 줄 열기',
        chapter: '삽입의 기술',
        description: 'o로 새로운 줄을 추가하세요.',
        initialText: 'first\nthird',
        targetText: 'first\nsecond\nthird',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['j', 'k', 'o'],
        maxMoves: 2,
        hint: 'o → second 입력',
        newCommands: ['o'],
    },

    // --- Chapter 5: 복사와 붙여넣기 ---
    {
        id: 10,
        stage: 1,
        title: '복제의 기술',
        chapter: '복사 & 붙여넣기',
        description: 'yy로 줄을 복사하고 p로 붙여넣으세요.',
        initialText: 'echo "hi"',
        targetText: 'echo "hi"\necho "hi"\necho "hi"',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['yy', 'p'],
        maxMoves: 4,
        hint: 'yy → p → p',
        newCommands: ['yy', 'p'],
    },
    {
        id: 11,
        stage: 1,
        title: '줄 재배치',
        chapter: '복사 & 붙여넣기',
        description: 'dd와 p를 조합하여 줄 순서를 바꾸세요.\ndd는 잘라내기처럼 동작합니다.',
        initialText: 'third\nfirst\nsecond',
        targetText: 'first\nsecond\nthird',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['j', 'k', 'dd', 'p', 'gg', 'G'],
        maxMoves: 6,
        hint: 'dd → G → p',
        newCommands: ['gg', 'G'],
    },

    // --- Chapter 6: 종합 도전 ---
    {
        id: 12,
        stage: 1,
        title: '최종 시험',
        chapter: '종합 도전',
        description: '모든 기술을 총동원하여\n코드를 완성하세요!',
        initialText: 'functon hi() {\n  retrun 1;\n\n}',
        targetText: 'function hi() {\n  return 1;\n}',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['h', 'j', 'k', 'l', 'w', 'b', 'x', 'i', 'dd', 'A', 'o', '0', '$', 'gg', 'G'],
        maxMoves: 16,
        hint: 'functon→function (i), retrun→return (x,i), 빈줄 dd',
        newCommands: [],
    },

    // ==========================================================
    // STAGE 2: Vim 고급 - 최적 해법의 발견
    // ==========================================================

    // --- Chapter 7: 검색과 교체의 기초 ---
    {
        id: 13,
        stage: 2,
        title: '문자 찾기',
        chapter: '검색과 교체',
        description: 'f{문자}로 줄 내 특정 문자 위치로 점프!\n세미콜론들을 콤마로 바꾸세요.',
        initialText: 'a;b;c;d',
        targetText: 'a,b,c,d',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['f', 'x', 'i', 'h', 'l'],
        maxMoves: 15,
        hint: 'f; → x → i → , → Esc 를 반복',
        newCommands: ['f'],
    },
    {
        id: 14,
        stage: 2,
        title: '문자 교체',
        chapter: '검색과 교체',
        description: 'r{문자}로 커서 위의 글자를 바로 교체!\nx+i보다 훨씬 빠릅니다.',
        initialText: 'hallo warld',
        targetText: 'hello world',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['r', 'h', 'l', 'w', 'f'],
        maxMoves: 6,
        hint: 'f로 a 위치에 점프 → r로 e로 교체 → w → f → r',
        newCommands: ['r'],
    },
    {
        id: 15,
        stage: 2,
        title: '찾기 반복',
        chapter: '검색과 교체',
        description: ';로 마지막 f/F 검색을 반복!\n같은 문자를 매번 f로 찾지 않아도 됩니다.',
        initialText: 'a.b.c.d.e',
        targetText: 'a-b-c-d-e',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['f', ';', 'r', 'l'],
        maxMoves: 10,
        hint: 'f. → r- → ; → r- → ; → r- → ; → r-',
        newCommands: [';'],
    },
    {
        id: 16,
        stage: 2,
        title: '변경 반복',
        chapter: '검색과 교체',
        description: '.으로 마지막 변경을 반복!\nr+;+. 조합의 위력을 느껴보세요.',
        initialText: 'x = 1 + 2 + 3 + 4',
        targetText: 'x = 1 - 2 - 3 - 4',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['f', ';', 'r', '.', 'l'],
        maxMoves: 7,
        hint: 'f+ → r- → ;. → ;. → ;.',
        newCommands: ['.'],
    },

    // --- Chapter 8: 효율의 발견 (콜백 레벨) ---
    {
        id: 17,
        stage: 2,
        title: '⚡ 문자 찾기 리턴',
        chapter: '효율의 발견',
        description: 'Level 13과 같은 유형!\n하지만 이번엔 횟수가 빡빡합니다.\n배운 기술을 총동원하세요.',
        initialText: 'a;b;c;d',
        targetText: 'a,b,c,d',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['f', ';', 'r', '.', 'h', 'l'],
        maxMoves: 6,
        hint: 'f; → r, → ;. → ;. (6수 클리어!)',
        newCommands: [],
    },
    {
        id: 18,
        stage: 2,
        title: '단어 교체',
        chapter: '효율의 발견',
        description: 'cw로 커서부터 단어 끝까지 삭제 후\n삽입 모드로 전환됩니다.',
        initialText: 'the cat sat\nthe cat ran',
        targetText: 'the dog sat\nthe dog ran',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['w', 'b', 'j', 'k', 'cw', '0'],
        maxMoves: 6,
        hint: 'w → cw → dog → Esc → j → 0 → w → cw → dog',
        newCommands: ['cw'],
    },
    {
        id: 19,
        stage: 2,
        title: '⚡ 연쇄 교체',
        chapter: '효율의 발견',
        description: '같은 단어를 여러 곳에서 교체!\ncw와 .을 조합하면?',
        initialText: 'foo bar\nfoo bar\nfoo bar',
        targetText: 'foo baz\nfoo baz\nfoo baz',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['w', 'j', 'cw', '.', '0'],
        maxMoves: 8,
        hint: 'w → cw → baz → Esc → j → 0 → w → . → j → 0 → w → .',
        newCommands: [],
    },

    // --- Chapter 9: 구조 편집 ---
    {
        id: 20,
        stage: 2,
        title: '괄호 안 변경',
        chapter: '구조 편집',
        description: 'ci(로 괄호 안 내용을 한 번에 변경!\ndi(로 삭제만 할 수도 있습니다.',
        initialText: 'foo(old)\nbar(delete)',
        targetText: 'foo(new)\nbar()',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['ci(', 'di(', 'j', 'w', 'h', 'l'],
        maxMoves: 5,
        hint: 'w → ci( → new → Esc → j → w → di(',
        newCommands: ['ci(', 'di('],
    },
    {
        id: 21,
        stage: 2,
        title: '따옴표 편집',
        chapter: '구조 편집',
        description: 'ci"로 따옴표 안을 한 번에 교체!\n문자열 내용을 바꾸세요.',
        initialText: 'msg = "hello"\nname = "world"',
        targetText: 'msg = "bye"\nname = "vim"',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['ci"', 'j', 'w', 'h', 'l'],
        maxMoves: 5,
        hint: 'ci" → bye → Esc → j → ci" → vim',
        newCommands: ['ci"'],
    },

    // --- Chapter 10: 비주얼 모드 ---
    {
        id: 22,
        stage: 2,
        title: '비주얼 선택',
        chapter: '비주얼 모드',
        description: 'v로 비주얼 모드 진입, 이동으로 선택,\nd로 선택 영역 삭제!',
        initialText: 'helloXXXworld',
        targetText: 'helloworld',
        initialCursor: { row: 0, col: 5 },
        allowedCommands: ['v', 'h', 'l', 'd'],
        maxMoves: 4,
        hint: 'v → ll → d (3글자 선택 후 삭제)',
        newCommands: ['v'],
    },
    {
        id: 23,
        stage: 2,
        title: '줄 비주얼',
        chapter: '비주얼 모드',
        description: 'V로 줄 단위 비주얼 모드!\n줄 전체를 선택하여 삭제하세요.',
        initialText: 'keep\nremove1\nremove2\nkeep too',
        targetText: 'keep\nkeep too',
        initialCursor: { row: 1, col: 0 },
        allowedCommands: ['V', 'j', 'k', 'd'],
        maxMoves: 3,
        hint: 'V → j → d (2줄 선택 후 삭제)',
        newCommands: ['V'],
    },

    // --- Chapter 11: 명령 모드 ---
    {
        id: 24,
        stage: 2,
        title: '검색과 교체',
        chapter: '명령 모드',
        description: ':s/찾을말/바꿀말 으로 현재 줄을 교체!\n:로 명령 모드에 진입합니다.',
        initialText: 'hello world\nhello vim',
        targetText: 'hi world\nhi vim',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: [':s', 'j'],
        maxMoves: 4,
        hint: ':s/hello/hi → Enter → j → :s/hello/hi → Enter',
        newCommands: [':s'],
    },

    // --- Chapter 12: 종합 도전 ---
    {
        id: 25,
        stage: 2,
        title: '⚡ 종합 도전',
        chapter: '종합 도전',
        description: '모든 기술을 총동원하여 코드를 완성!\nmaxMoves가 빡빡합니다.\n최적의 방법을 찾으세요.',
        initialText: 'function greet(name) {\n  var msg = "hello"\n  var out = "hello"\n  console.log(msg + naem)\n  return(undefined)\n}',
        targetText: 'function greet(name) {\n  const msg = "hi"\n  const out = "hi"\n  console.log(msg + name)\n  return(name)\n}',
        initialCursor: { row: 0, col: 0 },
        allowedCommands: ['h', 'j', 'k', 'l', 'w', 'b', 'f', ';', 'r', '.', 'cw', 'ci"', 'ci(', 'x', 'i', '0', '$'],
        maxMoves: 16,
        hint: 'j→w→cw const→Esc→j→0→w→.→ (cw 반복!)\nci"으로 문자열 교체, f/r로 오타 수정',
        newCommands: [],
    },
];

// Stage metadata
const STAGES = [
    {
        id: 1,
        title: 'STAGE 1',
        subtitle: 'Vim 기초',
        description: '기본 이동, 삽입, 삭제, 복사 등\nVim의 기본 명령어를 배웁니다.',
        color: 'var(--accent-green)',
    },
    {
        id: 2,
        title: 'STAGE 2',
        subtitle: 'Vim 고급',
        description: '검색 이동, 변경 명령, 비주얼 모드,\n명령 모드를 마스터합니다.',
        color: 'var(--accent-purple)',
    },
];

export { LEVELS, STAGES };
export default LEVELS;
